CRAGISLIST_URL = 'https://vancouver.craigslist.org'
CRAIGSLIST_SEARCH = 'https://vancouver.craigslist.org/search/sss'
CRAIGSLIST_SUGGESTIONS = CRAGISLIST_URL + '/suggest'
CRAIGSLIST_IMAGES = 'https://images.craigslist.org/'
NO_IMAGE = 'https://www.scott-sports.com/_ui/responsive/common/images/no-product-image-available.png'